apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: clinixiq
  labels:
    app.kubernetes.io/name: clinixiq-alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'service']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 4h
      receiver: 'webhook-receiver'
    receivers:
      - name: 'webhook-receiver'
        webhook_configs:
          - url: 'http://clinixiq-backend-service:8000/api/v1/alerts/webhook'
            send_resolved: true
