apiVersion: v1
kind: Secret
metadata:
  name: clinixiq-secrets
  namespace: clinixiq
  labels:
    app.kubernetes.io/name: clinixiq
    app.kubernetes.io/component: security
type: Opaque
stringData:
  REDIS_PASSWORD: "clinixiq-secure-redis-pass-token"
  API_SECRET_KEY: "clinixiq-jwt-session-encryption-key"
  STRIPE_SECRET_KEY: "clinixiq-stripe-secret-api-key-mock"
  STRIPE_PUBLISHABLE_KEY: "clinixiq-stripe-publishable-key-mock"
  STRIPE_WEBHOOK_SECRET: "whsec_clinixiq_production_mock_token"
