apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clinixiq-backend-servicemonitor
  namespace: clinixiq
  labels:
    app.kubernetes.io/name: clinixiq
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: clinixiq
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clinixiq-frontend-servicemonitor
  namespace: clinixiq
  labels:
    app.kubernetes.io/name: clinixiq
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: clinixiq
      app.kubernetes.io/component: frontend
  endpoints:
    - port: http
      path: /healthz
      interval: 30s
      scrapeTimeout: 5s
